Vagrant.configure("2") do |config|
  # 基础镜像
  config.vm.box = "ubuntu/xenial64"
  config.disksize.size = '40GB'

  # 配置网络
  config.vm.network "private_network", type: "dhcp"

  # 使用 nfs 速度更快一些
  config.vm.synced_folder "../share", "/vagrant", type: "nfs"

  # 初始环境的 Setup
  config.vm.provision "file", source: "./repo", destination: "/tmp/repo"
  config.vm.provision "file", source: "./install_zsh.sh", destination: "/tmp/install_zsh.sh"
  config.vm.provision "shell", path: "./setup.sh"

  # 配置 8096 平台的 USB 配置
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbxhci", "on"]
    vb.customize ["usbfilter", "add", "0", "--target", :id, "--name", "APQ8096", "--vendorid", "0x05c6", "--productid", "0x901d"]
    vb.customize ["usbfilter", "add", "0", "--target", :id, "--name", "Hover Camera", "--vendorid", "0x2cc0", "--productid", "0x0101"]
    vb.customize ["usbfilter", "add", "0", "--target", :id, "--name", "Qualcomm", "--vendorid", "0x05c6", "--productid", "0x9025"]

    vb.memory = 2048

    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 50]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant-root", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end
end
